CREATE TABLE IF NOT EXISTS public.driver_rest_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rest_id text NOT NULL UNIQUE,
    plan_id bigint REFERENCES public.dispatch_plans(id) ON DELETE SET NULL,
    plan_date date,
    driver_login text NOT NULL,
    truck_id text,
    truck_plate text,
    load_id text,
    load_name text,
    previous_job_id text,
    next_job_id text,
    status text NOT NULL DEFAULT 'active',
    started_at timestamptz NOT NULL DEFAULT now(),
    ended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_driver_rest_records_driver_active
  ON public.driver_rest_records (driver_login, status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_driver_rest_records_plan_load
  ON public.driver_rest_records (plan_id, load_id, started_at DESC);
