-- MBT Phase 1 rate, quote, contract, service-visit, evidence, distance, and
-- exact asset-reservation foundations. All monetary values are integer minor
-- units; UUID values are generated by the Node application.

CREATE TABLE IF NOT EXISTS mbt_rate_cards (
  rate_card_id uuid PRIMARY KEY,
  rate_card_code text NOT NULL UNIQUE,
  display_name text NOT NULL,
  customer_netsuite_id bigint REFERENCES netsuite_customers(netsuite_id) ON DELETE RESTRICT,
  subsidiary_netsuite_id bigint,
  service_template_id uuid REFERENCES mbt_service_templates(template_id) ON DELETE RESTRICT,
  currency text NOT NULL DEFAULT 'CAD',
  description text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  revision bigint NOT NULL DEFAULT 1,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_rate_cards_code_not_blank
    CHECK (NULLIF(btrim(rate_card_code), '') IS NOT NULL),
  CONSTRAINT mbt_rate_cards_name_not_blank
    CHECK (NULLIF(btrim(display_name), '') IS NOT NULL),
  CONSTRAINT mbt_rate_cards_subsidiary_positive
    CHECK (subsidiary_netsuite_id IS NULL OR subsidiary_netsuite_id > 0),
  CONSTRAINT mbt_rate_cards_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT mbt_rate_cards_revision_positive
    CHECK (revision > 0)
);

CREATE INDEX IF NOT EXISTS idx_mbt_rate_cards_selection
  ON mbt_rate_cards (
    active,
    COALESCE(customer_netsuite_id, 0),
    COALESCE(subsidiary_netsuite_id, 0),
    rate_card_code
  );

CREATE TABLE IF NOT EXISTS mbt_rate_card_versions (
  rate_card_version_id uuid PRIMARY KEY,
  rate_card_id uuid NOT NULL REFERENCES mbt_rate_cards(rate_card_id) ON DELETE RESTRICT,
  version_number integer NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  effective_from timestamptz,
  effective_to timestamptz,
  default_rental_calendar_days integer NOT NULL DEFAULT 14,
  calculation_notes text NOT NULL DEFAULT '',
  validation_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  activated_at timestamptz,
  retired_at timestamptz,
  first_used_at timestamptz,
  first_used_entity_type text,
  first_used_entity_id uuid,
  revision bigint NOT NULL DEFAULT 1,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_rate_card_versions_number_positive
    CHECK (version_number > 0),
  CONSTRAINT mbt_rate_card_versions_status
    CHECK (status IN ('draft', 'active', 'retired')),
  CONSTRAINT mbt_rate_card_versions_effective_order
    CHECK (effective_from IS NULL OR effective_to IS NULL OR effective_to > effective_from),
  CONSTRAINT mbt_rate_card_versions_rental_days_positive
    CHECK (default_rental_calendar_days > 0),
  CONSTRAINT mbt_rate_card_versions_validation_object
    CHECK (jsonb_typeof(validation_snapshot) = 'object'),
  CONSTRAINT mbt_rate_card_versions_active_fields
    CHECK (
      status <> 'active'
      OR (effective_from IS NOT NULL AND activated_at IS NOT NULL)
    ),
  CONSTRAINT mbt_rate_card_versions_retired_fields
    CHECK (status <> 'retired' OR retired_at IS NOT NULL),
  CONSTRAINT mbt_rate_card_versions_first_use_identity
    CHECK (
      (first_used_at IS NULL AND first_used_entity_type IS NULL AND first_used_entity_id IS NULL)
      OR
      (
        first_used_at IS NOT NULL
        AND NULLIF(btrim(COALESCE(first_used_entity_type, '')), '') IS NOT NULL
        AND first_used_entity_id IS NOT NULL
      )
    ),
  CONSTRAINT mbt_rate_card_versions_revision_positive
    CHECK (revision > 0),
  CONSTRAINT mbt_rate_card_versions_card_version_unique
    UNIQUE (rate_card_id, version_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_rate_card_versions_active
  ON mbt_rate_card_versions (rate_card_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_mbt_rate_card_versions_effective
  ON mbt_rate_card_versions (rate_card_id, status, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS mbt_rate_distance_bands (
  rate_distance_band_id uuid PRIMARY KEY,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  service_code text NOT NULL,
  bin_type_id uuid REFERENCES mbt_bin_types(bin_type_id) ON DELETE RESTRICT,
  sequence_number integer NOT NULL,
  minimum_metres bigint NOT NULL,
  maximum_metres bigint,
  amount_minor bigint NOT NULL,
  currency text NOT NULL DEFAULT 'CAD',
  downtown_surcharge_minor bigint NOT NULL DEFAULT 0,
  description text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_rate_distance_bands_service_code_format
    CHECK (service_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_rate_distance_bands_sequence_nonnegative
    CHECK (sequence_number >= 0),
  CONSTRAINT mbt_rate_distance_bands_minimum_nonnegative
    CHECK (minimum_metres >= 0),
  CONSTRAINT mbt_rate_distance_bands_range_order
    CHECK (maximum_metres IS NULL OR maximum_metres > minimum_metres),
  CONSTRAINT mbt_rate_distance_bands_amount_nonnegative
    CHECK (amount_minor >= 0 AND downtown_surcharge_minor >= 0),
  CONSTRAINT mbt_rate_distance_bands_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_rate_distance_bands_sequence
  ON mbt_rate_distance_bands (
    rate_card_version_id,
    service_code,
    COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid),
    sequence_number
  );

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_rate_distance_bands_minimum
  ON mbt_rate_distance_bands (
    rate_card_version_id,
    service_code,
    COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid),
    minimum_metres
  );

CREATE INDEX IF NOT EXISTS idx_mbt_rate_distance_bands_lookup
  ON mbt_rate_distance_bands (
    rate_card_version_id,
    service_code,
    bin_type_id,
    minimum_metres,
    maximum_metres
  );

CREATE TABLE IF NOT EXISTS mbt_rate_components (
  rate_component_id uuid PRIMARY KEY,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  component_code text NOT NULL,
  component_kind text NOT NULL,
  service_code text,
  bin_type_id uuid REFERENCES mbt_bin_types(bin_type_id) ON DELETE RESTRICT,
  rate_basis text NOT NULL DEFAULT 'flat',
  amount_minor bigint,
  percentage_basis_points integer,
  default_quantity numeric(14, 4) NOT NULL DEFAULT 1,
  currency text NOT NULL DEFAULT 'CAD',
  taxable boolean NOT NULL DEFAULT true,
  active boolean NOT NULL DEFAULT true,
  description text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_rate_components_code_format
    CHECK (component_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_rate_components_kind
    CHECK (
      component_kind IN (
        'base_transport', 'rental', 'extension', 'exchange', 'pickup',
        'downtown_surcharge', 'service', 'other'
      )
    ),
  CONSTRAINT mbt_rate_components_service_code_format
    CHECK (service_code IS NULL OR service_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_rate_components_basis
    CHECK (rate_basis IN ('flat', 'per_day', 'per_week', 'per_unit', 'percentage')),
  CONSTRAINT mbt_rate_components_value_shape
    CHECK (
      (
        rate_basis = 'percentage'
        AND amount_minor IS NULL
        AND percentage_basis_points IS NOT NULL
        AND percentage_basis_points BETWEEN 0 AND 1000000
      )
      OR
      (
        rate_basis <> 'percentage'
        AND amount_minor IS NOT NULL
        AND amount_minor >= 0
        AND percentage_basis_points IS NULL
      )
    ),
  CONSTRAINT mbt_rate_components_quantity_positive
    CHECK (default_quantity > 0),
  CONSTRAINT mbt_rate_components_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_rate_components_scope_unique
  ON mbt_rate_components (
    rate_card_version_id,
    component_code,
    COALESCE(service_code, ''),
    COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

CREATE TABLE IF NOT EXISTS mbt_dump_tariffs (
  dump_tariff_id uuid PRIMARY KEY,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  dump_site_id uuid NOT NULL REFERENCES mbt_dump_sites(dump_site_id) ON DELETE RESTRICT,
  material_id uuid REFERENCES mbt_materials(material_id) ON DELETE RESTRICT,
  tariff_code text NOT NULL,
  pricing_basis text NOT NULL,
  unit_of_measure text,
  amount_minor bigint NOT NULL,
  minimum_amount_minor bigint NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'CAD',
  active boolean NOT NULL DEFAULT true,
  description text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_dump_tariffs_code_format
    CHECK (tariff_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_dump_tariffs_basis
    CHECK (pricing_basis IN ('fixed', 'per_weight', 'per_quantity')),
  CONSTRAINT mbt_dump_tariffs_unit_shape
    CHECK (
      (pricing_basis = 'fixed' AND unit_of_measure IS NULL)
      OR
      (
        pricing_basis IN ('per_weight', 'per_quantity')
        AND NULLIF(btrim(COALESCE(unit_of_measure, '')), '') IS NOT NULL
      )
    ),
  CONSTRAINT mbt_dump_tariffs_amount_nonnegative
    CHECK (amount_minor >= 0 AND minimum_amount_minor >= 0),
  CONSTRAINT mbt_dump_tariffs_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_dump_tariffs_scope_unique
  ON mbt_dump_tariffs (
    rate_card_version_id,
    dump_site_id,
    COALESCE(material_id, '00000000-0000-0000-0000-000000000000'::uuid),
    tariff_code
  );

CREATE TABLE IF NOT EXISTS mbt_deposit_rules (
  deposit_rule_id uuid PRIMARY KEY,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  rule_code text NOT NULL,
  rule_type text NOT NULL,
  bin_type_id uuid REFERENCES mbt_bin_types(bin_type_id) ON DELETE RESTRICT,
  service_code text,
  fixed_amount_minor bigint,
  percentage_basis_points integer,
  currency text NOT NULL DEFAULT 'CAD',
  liability_account_mapping_key text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  description text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_deposit_rules_code_format
    CHECK (rule_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_deposit_rules_type
    CHECK (rule_type IN ('fixed', 'percentage', 'bin_type', 'service', 'customer_override')),
  CONSTRAINT mbt_deposit_rules_service_code_format
    CHECK (service_code IS NULL OR service_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_deposit_rules_value_shape
    CHECK (
      (
        rule_type = 'percentage'
        AND fixed_amount_minor IS NULL
        AND percentage_basis_points IS NOT NULL
        AND percentage_basis_points BETWEEN 0 AND 1000000
      )
      OR
      (
        rule_type <> 'percentage'
        AND fixed_amount_minor IS NOT NULL
        AND fixed_amount_minor >= 0
        AND percentage_basis_points IS NULL
      )
    ),
  CONSTRAINT mbt_deposit_rules_scope_shape
    CHECK (
      (rule_type <> 'bin_type' OR bin_type_id IS NOT NULL)
      AND
      (rule_type <> 'service' OR NULLIF(btrim(COALESCE(service_code, '')), '') IS NOT NULL)
    ),
  CONSTRAINT mbt_deposit_rules_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_deposit_rules_scope_unique
  ON mbt_deposit_rules (
    rate_card_version_id,
    rule_code,
    COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid),
    COALESCE(service_code, '')
  );

CREATE TABLE IF NOT EXISTS mbt_distance_snapshots (
  distance_snapshot_id uuid PRIMARY KEY,
  subject_type text NOT NULL,
  subject_id uuid NOT NULL,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  rate_distance_band_id uuid REFERENCES mbt_rate_distance_bands(rate_distance_band_id) ON DELETE RESTRICT,
  provider text NOT NULL,
  provider_metres bigint NOT NULL,
  route_hash text NOT NULL,
  origin_snapshot jsonb NOT NULL,
  destination_snapshot jsonb NOT NULL,
  route_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  calculated_amount_minor bigint NOT NULL,
  currency text NOT NULL DEFAULT 'CAD',
  override_metres bigint,
  override_amount_minor bigint,
  override_reason text,
  overridden_by text,
  overridden_at timestamptz,
  calculated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_distance_snapshots_subject_type
    CHECK (subject_type IN ('quote', 'contract', 'visit', 'billing', 'cross_charge')),
  CONSTRAINT mbt_distance_snapshots_provider_not_blank
    CHECK (NULLIF(btrim(provider), '') IS NOT NULL),
  CONSTRAINT mbt_distance_snapshots_provider_metres_nonnegative
    CHECK (provider_metres >= 0),
  CONSTRAINT mbt_distance_snapshots_route_hash_sha256
    CHECK (route_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT mbt_distance_snapshots_json_objects
    CHECK (
      jsonb_typeof(origin_snapshot) = 'object'
      AND jsonb_typeof(destination_snapshot) = 'object'
      AND jsonb_typeof(route_snapshot) = 'object'
    ),
  CONSTRAINT mbt_distance_snapshots_amount_nonnegative
    CHECK (
      calculated_amount_minor >= 0
      AND (override_metres IS NULL OR override_metres >= 0)
      AND (override_amount_minor IS NULL OR override_amount_minor >= 0)
    ),
  CONSTRAINT mbt_distance_snapshots_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT mbt_distance_snapshots_override_complete
    CHECK (
      (
        override_metres IS NULL
        AND override_amount_minor IS NULL
        AND override_reason IS NULL
        AND overridden_by IS NULL
        AND overridden_at IS NULL
      )
      OR
      (
        override_metres IS NOT NULL
        AND override_amount_minor IS NOT NULL
        AND NULLIF(btrim(COALESCE(override_reason, '')), '') IS NOT NULL
        AND NULLIF(btrim(COALESCE(overridden_by, '')), '') IS NOT NULL
        AND overridden_at IS NOT NULL
      )
    ),
  CONSTRAINT mbt_distance_snapshots_subject_unique
    UNIQUE (subject_type, subject_id, distance_snapshot_id)
);

CREATE INDEX IF NOT EXISTS idx_mbt_distance_snapshots_subject
  ON mbt_distance_snapshots (subject_type, subject_id, calculated_at DESC);

CREATE TABLE IF NOT EXISTS mbt_quotes (
  quote_id uuid PRIMARY KEY,
  quote_number text NOT NULL UNIQUE,
  customer_netsuite_id bigint NOT NULL REFERENCES netsuite_customers(netsuite_id) ON DELETE RESTRICT,
  customer_site_profile_id uuid NOT NULL REFERENCES mbt_customer_site_profiles(site_profile_id) ON DELETE RESTRICT,
  service_template_version_id uuid NOT NULL REFERENCES mbt_service_template_versions(template_version_id) ON DELETE RESTRICT,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  bin_type_id uuid NOT NULL REFERENCES mbt_bin_types(bin_type_id) ON DELETE RESTRICT,
  distance_snapshot_id uuid REFERENCES mbt_distance_snapshots(distance_snapshot_id) ON DELETE RESTRICT,
  deposit_rule_id uuid REFERENCES mbt_deposit_rules(deposit_rule_id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'draft',
  proposed_delivery_at timestamptz,
  proposed_return_at timestamptz,
  valid_until timestamptz,
  customer_snapshot jsonb NOT NULL,
  site_snapshot jsonb NOT NULL,
  pricing_snapshot jsonb NOT NULL,
  deposit_required_minor bigint NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'CAD',
  issued_at timestamptz,
  accepted_at timestamptz,
  terminal_at timestamptz,
  revision bigint NOT NULL DEFAULT 1,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_quotes_number_not_blank
    CHECK (NULLIF(btrim(quote_number), '') IS NOT NULL),
  CONSTRAINT mbt_quotes_status
    CHECK (status IN ('draft', 'issued', 'accepted', 'rejected', 'expired', 'cancelled', 'converted')),
  CONSTRAINT mbt_quotes_dates_order
    CHECK (
      (proposed_delivery_at IS NULL OR proposed_return_at IS NULL OR proposed_return_at > proposed_delivery_at)
      AND (issued_at IS NULL OR valid_until IS NULL OR valid_until > issued_at)
    ),
  CONSTRAINT mbt_quotes_snapshots_object
    CHECK (
      jsonb_typeof(customer_snapshot) = 'object'
      AND jsonb_typeof(site_snapshot) = 'object'
      AND jsonb_typeof(pricing_snapshot) = 'object'
    ),
  CONSTRAINT mbt_quotes_deposit_nonnegative
    CHECK (deposit_required_minor >= 0),
  CONSTRAINT mbt_quotes_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT mbt_quotes_revision_positive
    CHECK (revision > 0)
);

CREATE INDEX IF NOT EXISTS idx_mbt_quotes_work
  ON mbt_quotes (status, valid_until, quote_id);

CREATE TABLE IF NOT EXISTS mbt_contracts (
  contract_id uuid PRIMARY KEY,
  contract_number text NOT NULL UNIQUE,
  quote_id uuid REFERENCES mbt_quotes(quote_id) ON DELETE RESTRICT,
  customer_netsuite_id bigint NOT NULL REFERENCES netsuite_customers(netsuite_id) ON DELETE RESTRICT,
  customer_site_profile_id uuid NOT NULL REFERENCES mbt_customer_site_profiles(site_profile_id) ON DELETE RESTRICT,
  service_template_version_id uuid NOT NULL REFERENCES mbt_service_template_versions(template_version_id) ON DELETE RESTRICT,
  rate_card_version_id uuid NOT NULL REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  bin_type_id uuid NOT NULL REFERENCES mbt_bin_types(bin_type_id) ON DELETE RESTRICT,
  deposit_rule_id uuid REFERENCES mbt_deposit_rules(deposit_rule_id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'draft',
  planned_delivery_at timestamptz,
  planned_return_at timestamptz,
  actual_delivery_completed_at timestamptz,
  actual_closed_at timestamptz,
  rental_calendar_days integer NOT NULL DEFAULT 14,
  customer_snapshot jsonb NOT NULL,
  site_snapshot jsonb NOT NULL,
  terms_snapshot jsonb NOT NULL,
  tax_snapshot jsonb NOT NULL,
  pricing_snapshot jsonb NOT NULL,
  deposit_required_minor bigint NOT NULL DEFAULT 0,
  deposit_override_minor bigint,
  deposit_override_reason text,
  deposit_overridden_by text,
  deposit_overridden_at timestamptz,
  currency text NOT NULL DEFAULT 'CAD',
  confirmed_at timestamptz,
  activated_at timestamptz,
  closed_at timestamptz,
  cancelled_at timestamptz,
  revision bigint NOT NULL DEFAULT 1,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_contracts_number_not_blank
    CHECK (NULLIF(btrim(contract_number), '') IS NOT NULL),
  CONSTRAINT mbt_contracts_status
    CHECK (status IN ('draft', 'quoted', 'confirmed', 'active', 'return_due', 'closing', 'closed', 'cancelled')),
  CONSTRAINT mbt_contracts_dates_order
    CHECK (
      (planned_delivery_at IS NULL OR planned_return_at IS NULL OR planned_return_at > planned_delivery_at)
      AND
      (actual_delivery_completed_at IS NULL OR actual_closed_at IS NULL OR actual_closed_at >= actual_delivery_completed_at)
    ),
  CONSTRAINT mbt_contracts_rental_days_positive
    CHECK (rental_calendar_days > 0),
  CONSTRAINT mbt_contracts_snapshots_object
    CHECK (
      jsonb_typeof(customer_snapshot) = 'object'
      AND jsonb_typeof(site_snapshot) = 'object'
      AND jsonb_typeof(terms_snapshot) = 'object'
      AND jsonb_typeof(tax_snapshot) = 'object'
      AND jsonb_typeof(pricing_snapshot) = 'object'
    ),
  CONSTRAINT mbt_contracts_deposit_nonnegative
    CHECK (
      deposit_required_minor >= 0
      AND (deposit_override_minor IS NULL OR deposit_override_minor >= 0)
    ),
  CONSTRAINT mbt_contracts_deposit_override_complete
    CHECK (
      (
        deposit_override_minor IS NULL
        AND deposit_override_reason IS NULL
        AND deposit_overridden_by IS NULL
        AND deposit_overridden_at IS NULL
      )
      OR
      (
        deposit_override_minor IS NOT NULL
        AND NULLIF(btrim(COALESCE(deposit_override_reason, '')), '') IS NOT NULL
        AND NULLIF(btrim(COALESCE(deposit_overridden_by, '')), '') IS NOT NULL
        AND deposit_overridden_at IS NOT NULL
      )
    ),
  CONSTRAINT mbt_contracts_currency_iso
    CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT mbt_contracts_revision_positive
    CHECK (revision > 0)
);

CREATE INDEX IF NOT EXISTS idx_mbt_contracts_customer_status
  ON mbt_contracts (customer_netsuite_id, status, contract_number);

CREATE INDEX IF NOT EXISTS idx_mbt_contracts_return_due
  ON mbt_contracts (status, planned_return_at, contract_id)
  WHERE status IN ('active', 'return_due');

CREATE TABLE IF NOT EXISTS mbt_contract_amendments (
  amendment_id uuid PRIMARY KEY,
  contract_id uuid NOT NULL REFERENCES mbt_contracts(contract_id) ON DELETE RESTRICT,
  amendment_number integer NOT NULL,
  amendment_type text NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  rate_card_version_id uuid REFERENCES mbt_rate_card_versions(rate_card_version_id) ON DELETE RESTRICT,
  reason text NOT NULL,
  before_snapshot jsonb NOT NULL,
  after_snapshot jsonb NOT NULL,
  requested_effective_at timestamptz,
  approved_at timestamptz,
  approved_by text,
  rejected_at timestamptz,
  cancelled_at timestamptz,
  revision bigint NOT NULL DEFAULT 1,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_contract_amendments_number_positive
    CHECK (amendment_number > 0),
  CONSTRAINT mbt_contract_amendments_type
    CHECK (
      amendment_type IN (
        'extension', 'swap_exchange', 'same_bin_exchange', 'early_pickup',
        'return', 'service_change', 'customer_change', 'emergency_reroute', 'other'
      )
    ),
  CONSTRAINT mbt_contract_amendments_status
    CHECK (status IN ('draft', 'pending_approval', 'approved', 'rejected', 'cancelled')),
  CONSTRAINT mbt_contract_amendments_reason_not_blank
    CHECK (NULLIF(btrim(reason), '') IS NOT NULL),
  CONSTRAINT mbt_contract_amendments_snapshots_object
    CHECK (jsonb_typeof(before_snapshot) = 'object' AND jsonb_typeof(after_snapshot) = 'object'),
  CONSTRAINT mbt_contract_amendments_approval_complete
    CHECK (
      status <> 'approved'
      OR
      (
        approved_at IS NOT NULL
        AND NULLIF(btrim(COALESCE(approved_by, '')), '') IS NOT NULL
      )
    ),
  CONSTRAINT mbt_contract_amendments_revision_positive
    CHECK (revision > 0),
  CONSTRAINT mbt_contract_amendments_contract_number_unique
    UNIQUE (contract_id, amendment_number)
);

CREATE TABLE IF NOT EXISTS mbt_service_visits (
  service_visit_id uuid PRIMARY KEY,
  contract_id uuid NOT NULL REFERENCES mbt_contracts(contract_id) ON DELETE RESTRICT,
  amendment_id uuid REFERENCES mbt_contract_amendments(amendment_id) ON DELETE RESTRICT,
  visit_number integer NOT NULL,
  visit_reference text NOT NULL UNIQUE,
  service_template_version_id uuid NOT NULL REFERENCES mbt_service_template_versions(template_version_id) ON DELETE RESTRICT,
  service_action text NOT NULL,
  status text NOT NULL DEFAULT 'tentative',
  customer_site_profile_id uuid NOT NULL REFERENCES mbt_customer_site_profiles(site_profile_id) ON DELETE RESTRICT,
  bin_type_id uuid NOT NULL REFERENCES mbt_bin_types(bin_type_id) ON DELETE RESTRICT,
  expected_asset_id uuid REFERENCES mbt_bin_assets(asset_id) ON DELETE RESTRICT,
  outgoing_asset_id uuid REFERENCES mbt_bin_assets(asset_id) ON DELETE RESTRICT,
  incoming_asset_id uuid REFERENCES mbt_bin_assets(asset_id) ON DELETE RESTRICT,
  dump_site_id uuid REFERENCES mbt_dump_sites(dump_site_id) ON DELETE RESTRICT,
  material_id uuid REFERENCES mbt_materials(material_id) ON DELETE RESTRICT,
  planned_truck_id bigint REFERENCES dispatch_trucks(id) ON DELETE RESTRICT,
  planned_driver_id bigint REFERENCES dispatch_drivers(id) ON DELETE RESTRICT,
  scheduled_start_at timestamptz,
  scheduled_end_at timestamptz,
  actual_started_at timestamptz,
  actual_completed_at timestamptz,
  customer_snapshot jsonb NOT NULL,
  site_snapshot jsonb NOT NULL,
  service_snapshot jsonb NOT NULL,
  billing_ownership text NOT NULL DEFAULT 'customer',
  billing_exception boolean NOT NULL DEFAULT false,
  billing_exception_reason text,
  dispatch_order_reference text,
  dispatch_plan_id text,
  dispatch_plan_revision bigint,
  cancelled_at timestamptz,
  cancellation_reason text,
  revision bigint NOT NULL DEFAULT 1,
  created_by text,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_service_visits_number_positive
    CHECK (visit_number > 0),
  CONSTRAINT mbt_service_visits_reference_not_blank
    CHECK (NULLIF(btrim(visit_reference), '') IS NOT NULL),
  CONSTRAINT mbt_service_visits_action_format
    CHECK (service_action ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_service_visits_status
    CHECK (status IN ('tentative', 'ready', 'planned', 'in_progress', 'evidence_pending', 'completed', 'cancelled')),
  CONSTRAINT mbt_service_visits_schedule_order
    CHECK (scheduled_start_at IS NULL OR scheduled_end_at IS NULL OR scheduled_end_at > scheduled_start_at),
  CONSTRAINT mbt_service_visits_actual_order
    CHECK (actual_started_at IS NULL OR actual_completed_at IS NULL OR actual_completed_at >= actual_started_at),
  CONSTRAINT mbt_service_visits_billing_ownership
    CHECK (billing_ownership IN ('customer', 'mbt', 'mbbs', 'shared', 'none')),
  CONSTRAINT mbt_service_visits_billing_exception_reason
    CHECK (NOT billing_exception OR NULLIF(btrim(COALESCE(billing_exception_reason, '')), '') IS NOT NULL),
  CONSTRAINT mbt_service_visits_dispatch_revision_positive
    CHECK (dispatch_plan_revision IS NULL OR dispatch_plan_revision > 0),
  CONSTRAINT mbt_service_visits_cancel_complete
    CHECK (
      status <> 'cancelled'
      OR
      (
        cancelled_at IS NOT NULL
        AND NULLIF(btrim(COALESCE(cancellation_reason, '')), '') IS NOT NULL
      )
    ),
  CONSTRAINT mbt_service_visits_snapshots_object
    CHECK (
      jsonb_typeof(customer_snapshot) = 'object'
      AND jsonb_typeof(site_snapshot) = 'object'
      AND jsonb_typeof(service_snapshot) = 'object'
    ),
  CONSTRAINT mbt_service_visits_revision_positive
    CHECK (revision > 0),
  CONSTRAINT mbt_service_visits_contract_number_unique
    UNIQUE (contract_id, visit_number)
);

CREATE INDEX IF NOT EXISTS idx_mbt_service_visits_dispatch
  ON mbt_service_visits (status, scheduled_start_at, service_visit_id)
  WHERE status IN ('ready', 'planned', 'in_progress', 'evidence_pending');

CREATE INDEX IF NOT EXISTS idx_mbt_service_visits_contract_timeline
  ON mbt_service_visits (contract_id, visit_number, service_visit_id);

CREATE TABLE IF NOT EXISTS mbt_visit_steps (
  visit_step_id uuid PRIMARY KEY,
  service_visit_id uuid NOT NULL REFERENCES mbt_service_visits(service_visit_id) ON DELETE RESTRICT,
  template_step_id uuid REFERENCES mbt_service_template_steps(template_step_id) ON DELETE RESTRICT,
  sequence_number integer NOT NULL,
  action_code text NOT NULL,
  display_name text NOT NULL,
  location_role text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  required boolean NOT NULL DEFAULT true,
  completion_blocking boolean NOT NULL DEFAULT true,
  expected_asset_id uuid REFERENCES mbt_bin_assets(asset_id) ON DELETE RESTRICT,
  verified_asset_id uuid REFERENCES mbt_bin_assets(asset_id) ON DELETE RESTRICT,
  started_at timestamptz,
  completed_at timestamptz,
  skipped_reason text,
  revision bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_visit_steps_sequence_nonnegative
    CHECK (sequence_number >= 0),
  CONSTRAINT mbt_visit_steps_action_format
    CHECK (action_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_visit_steps_name_not_blank
    CHECK (NULLIF(btrim(display_name), '') IS NOT NULL),
  CONSTRAINT mbt_visit_steps_location_not_blank
    CHECK (NULLIF(btrim(location_role), '') IS NOT NULL),
  CONSTRAINT mbt_visit_steps_status
    CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'cancelled')),
  CONSTRAINT mbt_visit_steps_completion_order
    CHECK (started_at IS NULL OR completed_at IS NULL OR completed_at >= started_at),
  CONSTRAINT mbt_visit_steps_skip_reason
    CHECK (status <> 'skipped' OR NULLIF(btrim(COALESCE(skipped_reason, '')), '') IS NOT NULL),
  CONSTRAINT mbt_visit_steps_revision_positive
    CHECK (revision > 0),
  CONSTRAINT mbt_visit_steps_sequence_unique
    UNIQUE (service_visit_id, sequence_number),
  CONSTRAINT mbt_visit_steps_action_unique
    UNIQUE (service_visit_id, action_code)
);

CREATE TABLE IF NOT EXISTS mbt_visit_evidence_requirements (
  visit_evidence_requirement_id uuid PRIMARY KEY,
  service_visit_id uuid NOT NULL REFERENCES mbt_service_visits(service_visit_id) ON DELETE RESTRICT,
  visit_step_id uuid REFERENCES mbt_visit_steps(visit_step_id) ON DELETE RESTRICT,
  template_evidence_requirement_id uuid REFERENCES mbt_service_template_evidence_requirements(evidence_requirement_id) ON DELETE RESTRICT,
  evidence_code text NOT NULL,
  evidence_type text NOT NULL,
  minimum_count integer NOT NULL DEFAULT 1,
  required boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'pending',
  waiver_reason text,
  waived_by text,
  waived_at timestamptz,
  revision bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_visit_evidence_requirements_code_format
    CHECK (evidence_code ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_visit_evidence_requirements_type
    CHECK (evidence_type IN ('photo', 'receipt', 'bin_scan', 'weight', 'quantity', 'signature', 'note')),
  CONSTRAINT mbt_visit_evidence_requirements_count_positive
    CHECK (minimum_count > 0),
  CONSTRAINT mbt_visit_evidence_requirements_status
    CHECK (status IN ('pending', 'satisfied', 'waived')),
  CONSTRAINT mbt_visit_evidence_requirements_waiver_complete
    CHECK (
      status <> 'waived'
      OR
      (
        NULLIF(btrim(COALESCE(waiver_reason, '')), '') IS NOT NULL
        AND NULLIF(btrim(COALESCE(waived_by, '')), '') IS NOT NULL
        AND waived_at IS NOT NULL
      )
    ),
  CONSTRAINT mbt_visit_evidence_requirements_revision_positive
    CHECK (revision > 0),
  CONSTRAINT mbt_visit_evidence_requirements_unique
    UNIQUE (service_visit_id, visit_step_id, evidence_code)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_visit_evidence_global_unique
  ON mbt_visit_evidence_requirements (service_visit_id, evidence_code)
  WHERE visit_step_id IS NULL;

CREATE TABLE IF NOT EXISTS mbt_evidence (
  evidence_id uuid PRIMARY KEY,
  service_visit_id uuid NOT NULL REFERENCES mbt_service_visits(service_visit_id) ON DELETE RESTRICT,
  visit_step_id uuid REFERENCES mbt_visit_steps(visit_step_id) ON DELETE RESTRICT,
  visit_evidence_requirement_id uuid REFERENCES mbt_visit_evidence_requirements(visit_evidence_requirement_id) ON DELETE RESTRICT,
  evidence_type text NOT NULL,
  storage_provider text NOT NULL,
  storage_key text NOT NULL,
  content_sha256 text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  quantity numeric(18, 6),
  unit_of_measure text,
  amount_minor bigint,
  currency text,
  captured_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  captured_by_type text NOT NULL,
  captured_by_id text,
  source text NOT NULL,
  review_status text NOT NULL DEFAULT 'pending',
  reviewed_by text,
  reviewed_at timestamptz,
  review_note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  revision bigint NOT NULL DEFAULT 1,
  CONSTRAINT mbt_evidence_type
    CHECK (evidence_type IN ('photo', 'receipt', 'bin_scan', 'weight', 'quantity', 'signature', 'note')),
  CONSTRAINT mbt_evidence_storage_provider_not_blank
    CHECK (NULLIF(btrim(storage_provider), '') IS NOT NULL),
  CONSTRAINT mbt_evidence_storage_key_not_blank
    CHECK (NULLIF(btrim(storage_key), '') IS NOT NULL),
  CONSTRAINT mbt_evidence_hash_sha256
    CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT mbt_evidence_mime_not_blank
    CHECK (NULLIF(btrim(mime_type), '') IS NOT NULL),
  CONSTRAINT mbt_evidence_size_nonnegative
    CHECK (size_bytes >= 0),
  CONSTRAINT mbt_evidence_quantity_shape
    CHECK (
      (quantity IS NULL AND unit_of_measure IS NULL)
      OR
      (quantity IS NOT NULL AND quantity >= 0 AND NULLIF(btrim(COALESCE(unit_of_measure, '')), '') IS NOT NULL)
    ),
  CONSTRAINT mbt_evidence_amount_shape
    CHECK (
      (amount_minor IS NULL AND currency IS NULL)
      OR
      (amount_minor IS NOT NULL AND amount_minor >= 0 AND currency ~ '^[A-Z]{3}$')
    ),
  CONSTRAINT mbt_evidence_actor_type_not_blank
    CHECK (NULLIF(btrim(captured_by_type), '') IS NOT NULL),
  CONSTRAINT mbt_evidence_source_not_blank
    CHECK (NULLIF(btrim(source), '') IS NOT NULL),
  CONSTRAINT mbt_evidence_review_status
    CHECK (review_status IN ('pending', 'accepted', 'rejected', 'not_required')),
  CONSTRAINT mbt_evidence_review_complete
    CHECK (
      review_status = 'pending'
      OR
      (
        NULLIF(btrim(COALESCE(reviewed_by, '')), '') IS NOT NULL
        AND reviewed_at IS NOT NULL
      )
    ),
  CONSTRAINT mbt_evidence_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT mbt_evidence_revision_positive
    CHECK (revision > 0),
  CONSTRAINT mbt_evidence_storage_unique
    UNIQUE (storage_provider, storage_key)
);

CREATE INDEX IF NOT EXISTS idx_mbt_evidence_visit
  ON mbt_evidence (service_visit_id, visit_step_id, captured_at, evidence_id);

CREATE TABLE IF NOT EXISTS mbt_bin_asset_reservations (
  reservation_id uuid PRIMARY KEY,
  asset_id uuid NOT NULL REFERENCES mbt_bin_assets(asset_id) ON DELETE RESTRICT,
  contract_id uuid NOT NULL REFERENCES mbt_contracts(contract_id) ON DELETE RESTRICT,
  visit_id uuid NOT NULL REFERENCES mbt_service_visits(service_visit_id) ON DELETE RESTRICT,
  reservation_slot text NOT NULL,
  reserved_from timestamptz,
  reserved_until timestamptz,
  reserved_by text NOT NULL,
  reserved_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  released_by text,
  release_reason text,
  revision bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mbt_bin_asset_reservations_slot_format
    CHECK (reservation_slot ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT mbt_bin_asset_reservations_window_order
    CHECK (reserved_from IS NULL OR reserved_until IS NULL OR reserved_until > reserved_from),
  CONSTRAINT mbt_bin_asset_reservations_reserved_by_not_blank
    CHECK (NULLIF(btrim(reserved_by), '') IS NOT NULL),
  CONSTRAINT mbt_bin_asset_reservations_release_complete
    CHECK (
      (
        released_at IS NULL
        AND released_by IS NULL
        AND release_reason IS NULL
      )
      OR
      (
        released_at IS NOT NULL
        AND NULLIF(btrim(COALESCE(released_by, '')), '') IS NOT NULL
        AND NULLIF(btrim(COALESCE(release_reason, '')), '') IS NOT NULL
      )
    ),
  CONSTRAINT mbt_bin_asset_reservations_release_order
    CHECK (released_at IS NULL OR released_at >= reserved_at),
  CONSTRAINT mbt_bin_asset_reservations_revision_positive
    CHECK (revision > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_bin_asset_reservations_active_asset
  ON mbt_bin_asset_reservations (asset_id)
  WHERE released_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mbt_bin_asset_reservations_active_visit_slot
  ON mbt_bin_asset_reservations (visit_id, reservation_slot)
  WHERE released_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_mbt_bin_asset_reservations_visit
  ON mbt_bin_asset_reservations (visit_id, released_at, reservation_slot);

-- Composite identities keep independently valid foreign keys from being
-- combined into a semantically invalid rate, contract, visit, or evidence
-- relationship.
ALTER TABLE mbt_rate_distance_bands
  ADD CONSTRAINT mbt_rate_distance_bands_version_band_unique
  UNIQUE (rate_card_version_id, rate_distance_band_id);

ALTER TABLE mbt_deposit_rules
  ADD CONSTRAINT mbt_deposit_rules_version_rule_unique
  UNIQUE (rate_card_version_id, deposit_rule_id);

ALTER TABLE mbt_distance_snapshots
  ADD CONSTRAINT mbt_distance_snapshots_version_band_fk
  FOREIGN KEY (rate_card_version_id, rate_distance_band_id)
  REFERENCES mbt_rate_distance_bands(rate_card_version_id, rate_distance_band_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_quotes
  ADD CONSTRAINT mbt_quotes_version_deposit_rule_fk
  FOREIGN KEY (rate_card_version_id, deposit_rule_id)
  REFERENCES mbt_deposit_rules(rate_card_version_id, deposit_rule_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_contracts
  ADD CONSTRAINT mbt_contracts_version_deposit_rule_fk
  FOREIGN KEY (rate_card_version_id, deposit_rule_id)
  REFERENCES mbt_deposit_rules(rate_card_version_id, deposit_rule_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_contracts
  ADD CONSTRAINT mbt_contracts_customer_contract_unique
  UNIQUE (customer_netsuite_id, contract_id);

ALTER TABLE mbt_contract_amendments
  ADD CONSTRAINT mbt_contract_amendments_contract_id_unique
  UNIQUE (contract_id, amendment_id);

ALTER TABLE mbt_service_visits
  ADD CONSTRAINT mbt_service_visits_contract_visit_unique
  UNIQUE (contract_id, service_visit_id);

ALTER TABLE mbt_service_visits
  ADD CONSTRAINT mbt_service_visits_contract_amendment_fk
  FOREIGN KEY (contract_id, amendment_id)
  REFERENCES mbt_contract_amendments(contract_id, amendment_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_visit_steps
  ADD CONSTRAINT mbt_visit_steps_visit_step_unique
  UNIQUE (service_visit_id, visit_step_id);

ALTER TABLE mbt_visit_evidence_requirements
  ADD CONSTRAINT mbt_visit_evidence_requirements_visit_step_fk
  FOREIGN KEY (service_visit_id, visit_step_id)
  REFERENCES mbt_visit_steps(service_visit_id, visit_step_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_visit_evidence_requirements
  ADD CONSTRAINT mbt_visit_evidence_requirements_visit_id_unique
  UNIQUE (service_visit_id, visit_evidence_requirement_id);

ALTER TABLE mbt_evidence
  ADD CONSTRAINT mbt_evidence_visit_step_fk
  FOREIGN KEY (service_visit_id, visit_step_id)
  REFERENCES mbt_visit_steps(service_visit_id, visit_step_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_evidence
  ADD CONSTRAINT mbt_evidence_visit_requirement_fk
  FOREIGN KEY (service_visit_id, visit_evidence_requirement_id)
  REFERENCES mbt_visit_evidence_requirements(service_visit_id, visit_evidence_requirement_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_bin_asset_reservations
  ADD CONSTRAINT mbt_bin_asset_reservations_contract_visit_fk
  FOREIGN KEY (contract_id, visit_id)
  REFERENCES mbt_service_visits(contract_id, service_visit_id)
  ON DELETE RESTRICT;

ALTER TABLE mbt_bin_movements
  DROP CONSTRAINT IF EXISTS mbt_bin_movements_contract_fk;

ALTER TABLE mbt_bin_movements
  ADD CONSTRAINT mbt_bin_movements_contract_fk
  FOREIGN KEY (contract_id) REFERENCES mbt_contracts(contract_id) ON DELETE RESTRICT;

ALTER TABLE mbt_bin_movements
  DROP CONSTRAINT IF EXISTS mbt_bin_movements_service_visit_fk;

ALTER TABLE mbt_bin_movements
  ADD CONSTRAINT mbt_bin_movements_service_visit_fk
  FOREIGN KEY (service_visit_id) REFERENCES mbt_service_visits(service_visit_id) ON DELETE RESTRICT;

ALTER TABLE mbt_bin_movements
  ADD CONSTRAINT mbt_bin_movements_visit_requires_contract
  CHECK (service_visit_id IS NULL OR contract_id IS NOT NULL);

ALTER TABLE mbt_bin_movements
  ADD CONSTRAINT mbt_bin_movements_contract_visit_fk
  FOREIGN KEY (contract_id, service_visit_id)
  REFERENCES mbt_service_visits(contract_id, service_visit_id)
  ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION mbt_validate_rate_card_version_activation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  band_count integer;
  invalid_count integer;
BEGIN
  IF NEW.status <> 'active'
     OR (TG_OP = 'UPDATE' AND OLD.status = 'active') THEN
    RETURN NEW;
  END IF;

  WITH ordered_bands AS (
    SELECT minimum_metres,
           maximum_metres,
           row_number() OVER (
             PARTITION BY service_code,
                          COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid)
             ORDER BY minimum_metres, sequence_number, rate_distance_band_id
           ) AS band_position,
           count(*) OVER (
             PARTITION BY service_code,
                          COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid)
           ) AS group_size,
           lag(maximum_metres) OVER (
             PARTITION BY service_code,
                          COALESCE(bin_type_id, '00000000-0000-0000-0000-000000000000'::uuid)
             ORDER BY minimum_metres, sequence_number, rate_distance_band_id
           ) AS previous_maximum
      FROM mbt_rate_distance_bands
     WHERE rate_card_version_id = NEW.rate_card_version_id
  )
  SELECT count(*)::integer,
         count(*) FILTER (
           WHERE (band_position = 1 AND minimum_metres <> 0)
              OR (band_position > 1 AND previous_maximum IS DISTINCT FROM minimum_metres)
              OR (band_position < group_size AND maximum_metres IS NULL)
              OR (band_position = group_size AND maximum_metres IS NOT NULL)
         )::integer
    INTO band_count, invalid_count
    FROM ordered_bands;

  IF band_count = 0 OR invalid_count > 0 THEN
    RAISE EXCEPTION 'rate-card version % has invalid distance bands',
      NEW.rate_card_version_id
      USING ERRCODE = '23514',
            CONSTRAINT = 'mbt_rate_card_versions_distance_bands_valid';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_rate_card_versions_activation_valid
  ON mbt_rate_card_versions;
CREATE TRIGGER trg_mbt_rate_card_versions_activation_valid
  BEFORE INSERT OR UPDATE OF status ON mbt_rate_card_versions
  FOR EACH ROW EXECUTE FUNCTION mbt_validate_rate_card_version_activation();

CREATE OR REPLACE FUNCTION mbt_stamp_rate_version_first_use()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  entity_type text;
  entity_id uuid;
  version_status text;
BEGIN
  IF TG_TABLE_NAME = 'mbt_quotes' THEN
    IF NEW.status = 'draft' THEN
      RETURN NEW;
    END IF;
    entity_type := 'quote';
    entity_id := NEW.quote_id;
  ELSIF TG_TABLE_NAME = 'mbt_contracts' THEN
    IF NEW.status = 'draft' THEN
      RETURN NEW;
    END IF;
    entity_type := 'contract';
    entity_id := NEW.contract_id;
  ELSE
    RAISE EXCEPTION 'unsupported rate-version consumer %', TG_TABLE_NAME
      USING ERRCODE = '55000';
  END IF;

  SELECT status
    INTO version_status
    FROM mbt_rate_card_versions
   WHERE rate_card_version_id = NEW.rate_card_version_id
   FOR UPDATE;
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;
  IF version_status <> 'active' THEN
    RAISE EXCEPTION '% % cannot use non-active rate-card version %',
      entity_type, entity_id, NEW.rate_card_version_id
      USING ERRCODE = '55000';
  END IF;

  UPDATE mbt_rate_card_versions
     SET first_used_at = now(),
         first_used_entity_type = entity_type,
         first_used_entity_id = entity_id
   WHERE rate_card_version_id = NEW.rate_card_version_id
     AND first_used_at IS NULL;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_quotes_stamp_rate_first_use
  ON mbt_quotes;
CREATE TRIGGER trg_mbt_quotes_stamp_rate_first_use
  BEFORE INSERT OR UPDATE OF status, rate_card_version_id ON mbt_quotes
  FOR EACH ROW EXECUTE FUNCTION mbt_stamp_rate_version_first_use();

DROP TRIGGER IF EXISTS trg_mbt_contracts_stamp_rate_first_use
  ON mbt_contracts;
CREATE TRIGGER trg_mbt_contracts_stamp_rate_first_use
  BEFORE INSERT OR UPDATE OF status, rate_card_version_id ON mbt_contracts
  FOR EACH ROW EXECUTE FUNCTION mbt_stamp_rate_version_first_use();

CREATE OR REPLACE FUNCTION mbt_reject_used_rate_version_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.first_used_at IS NOT NULL THEN
    RAISE EXCEPTION 'used rate-card version % is immutable', OLD.rate_card_version_id
      USING ERRCODE = '55000';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION mbt_reject_used_rate_child_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  old_version_id uuid;
  new_version_id uuid;
  used_at timestamptz;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    old_version_id := OLD.rate_card_version_id;
    SELECT first_used_at
      INTO used_at
      FROM mbt_rate_card_versions
     WHERE rate_card_version_id = old_version_id;
    IF used_at IS NOT NULL THEN
      RAISE EXCEPTION 'pricing rows for used rate-card version % are immutable', old_version_id
        USING ERRCODE = '55000';
    END IF;
  END IF;

  IF TG_OP <> 'DELETE' THEN
    new_version_id := NEW.rate_card_version_id;
    IF old_version_id IS DISTINCT FROM new_version_id THEN
      SELECT first_used_at
        INTO used_at
        FROM mbt_rate_card_versions
       WHERE rate_card_version_id = new_version_id;
      IF used_at IS NOT NULL THEN
        RAISE EXCEPTION 'pricing rows for used rate-card version % are immutable', new_version_id
          USING ERRCODE = '55000';
      END IF;
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_rate_card_versions_used_immutable
  ON mbt_rate_card_versions;
CREATE TRIGGER trg_mbt_rate_card_versions_used_immutable
  BEFORE UPDATE OR DELETE ON mbt_rate_card_versions
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_used_rate_version_mutation();

DROP TRIGGER IF EXISTS trg_mbt_rate_distance_bands_used_immutable
  ON mbt_rate_distance_bands;
CREATE TRIGGER trg_mbt_rate_distance_bands_used_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_rate_distance_bands
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_used_rate_child_mutation();

DROP TRIGGER IF EXISTS trg_mbt_rate_components_used_immutable
  ON mbt_rate_components;
CREATE TRIGGER trg_mbt_rate_components_used_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_rate_components
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_used_rate_child_mutation();

DROP TRIGGER IF EXISTS trg_mbt_dump_tariffs_used_immutable
  ON mbt_dump_tariffs;
CREATE TRIGGER trg_mbt_dump_tariffs_used_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_dump_tariffs
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_used_rate_child_mutation();

DROP TRIGGER IF EXISTS trg_mbt_deposit_rules_used_immutable
  ON mbt_deposit_rules;
CREATE TRIGGER trg_mbt_deposit_rules_used_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_deposit_rules
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_used_rate_child_mutation();

DROP TRIGGER IF EXISTS trg_mbt_distance_snapshots_immutable
  ON mbt_distance_snapshots;
CREATE TRIGGER trg_mbt_distance_snapshots_immutable
  BEFORE UPDATE OR DELETE ON mbt_distance_snapshots
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_immutable_mutation();

CREATE OR REPLACE FUNCTION mbt_reject_completed_visit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'completed' THEN
    RAISE EXCEPTION 'completed service visit % is immutable', OLD.service_visit_id
      USING ERRCODE = '55000';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_service_visits_completed_immutable
  ON mbt_service_visits;
CREATE TRIGGER trg_mbt_service_visits_completed_immutable
  BEFORE UPDATE OR DELETE ON mbt_service_visits
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_completed_visit_mutation();

CREATE OR REPLACE FUNCTION mbt_reject_completed_visit_child_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  parent_visit_id uuid;
  parent_status text;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    parent_visit_id := OLD.service_visit_id;
    SELECT status
      INTO parent_status
      FROM mbt_service_visits
     WHERE service_visit_id = parent_visit_id;
    IF parent_status = 'completed' THEN
      RAISE EXCEPTION 'operational history for completed service visit % is immutable', parent_visit_id
        USING ERRCODE = '55000';
    END IF;
  END IF;

  IF TG_OP <> 'DELETE'
     AND (TG_OP = 'INSERT' OR NEW.service_visit_id IS DISTINCT FROM OLD.service_visit_id) THEN
    parent_visit_id := NEW.service_visit_id;
    SELECT status
      INTO parent_status
      FROM mbt_service_visits
     WHERE service_visit_id = parent_visit_id;
    IF parent_status = 'completed' THEN
      RAISE EXCEPTION 'operational history for completed service visit % is immutable', parent_visit_id
        USING ERRCODE = '55000';
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_visit_steps_completed_visit_immutable
  ON mbt_visit_steps;
CREATE TRIGGER trg_mbt_visit_steps_completed_visit_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_visit_steps
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_completed_visit_child_mutation();

DROP TRIGGER IF EXISTS trg_mbt_visit_evidence_requirements_completed_visit_immutable
  ON mbt_visit_evidence_requirements;
CREATE TRIGGER trg_mbt_visit_evidence_requirements_completed_visit_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_visit_evidence_requirements
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_completed_visit_child_mutation();

DROP TRIGGER IF EXISTS trg_mbt_evidence_completed_visit_immutable
  ON mbt_evidence;
CREATE TRIGGER trg_mbt_evidence_completed_visit_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON mbt_evidence
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_completed_visit_child_mutation();

CREATE OR REPLACE FUNCTION mbt_reject_terminal_visit_reservation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  visit_status text;
BEGIN
  SELECT status
    INTO visit_status
    FROM mbt_service_visits
   WHERE service_visit_id = NEW.visit_id;
  IF visit_status IN ('completed', 'cancelled') THEN
    RAISE EXCEPTION '% service visit % cannot accept an asset reservation',
      visit_status, NEW.visit_id
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_bin_asset_reservations_terminal_visit
  ON mbt_bin_asset_reservations;
CREATE TRIGGER trg_mbt_bin_asset_reservations_terminal_visit
  BEFORE INSERT OR UPDATE OF contract_id, visit_id ON mbt_bin_asset_reservations
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_terminal_visit_reservation();

CREATE OR REPLACE FUNCTION mbt_reject_released_reservation_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.released_at IS NOT NULL THEN
    RAISE EXCEPTION 'released asset reservation % is immutable', OLD.reservation_id
      USING ERRCODE = '55000';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_bin_asset_reservations_released_immutable
  ON mbt_bin_asset_reservations;
CREATE TRIGGER trg_mbt_bin_asset_reservations_released_immutable
  BEFORE UPDATE OR DELETE ON mbt_bin_asset_reservations
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_released_reservation_mutation();

CREATE OR REPLACE FUNCTION mbt_reject_approved_amendment_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'approved' THEN
    RAISE EXCEPTION 'approved contract amendment % is immutable', OLD.amendment_id
      USING ERRCODE = '55000';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mbt_contract_amendments_approved_immutable
  ON mbt_contract_amendments;
CREATE TRIGGER trg_mbt_contract_amendments_approved_immutable
  BEFORE UPDATE OR DELETE ON mbt_contract_amendments
  FOR EACH ROW EXECUTE FUNCTION mbt_reject_approved_amendment_mutation();

COMMENT ON TABLE mbt_rate_card_versions IS
  'Effective-dated MBT pricing versions. Marking first_used_at locks the version and every pricing child row.';

COMMENT ON TABLE mbt_service_visits IS
  'Independently schedulable MBT work projected to Dispatch only after later-phase capabilities are enabled.';

COMMENT ON TABLE mbt_bin_asset_reservations IS
  'Exact-bin reservations. Partial unique indexes prevent one asset or one visit slot from being reserved twice.';
