ALTER TABLE operators ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT '';
ALTER TABLE operators DROP CONSTRAINT IF EXISTS operators_role_check;
ALTER TABLE operators ADD CONSTRAINT operators_role_check CHECK (role IN
 ('operator','dispatcher','admin','scm','yard_manager','sales','field_sales','mbt_frontdesk','mbt_billing','boss'));
ALTER TABLE operators DROP CONSTRAINT IF EXISTS operators_roles_allowed_check;
ALTER TABLE operators ADD CONSTRAINT operators_roles_allowed_check CHECK
 (cardinality(roles)>0 AND role=ANY(roles) AND roles <@ ARRAY['operator','dispatcher','admin','scm','yard_manager','sales','field_sales','mbt_frontdesk','mbt_billing','boss']::text[]);

CREATE TABLE IF NOT EXISTS boss_approval_settings (
 id integer PRIMARY KEY CHECK(id=1), enabled boolean NOT NULL DEFAULT false,
 revision bigint NOT NULL DEFAULT 1, bootstrap_complete boolean NOT NULL DEFAULT false,
 updated_by text REFERENCES operators(id), updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO boss_approval_settings(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS boss_approval_principals (
 key text PRIMARY KEY CHECK(key IN ('tony_tan','jason_pu','alex_huang')),
 name text NOT NULL, owner_id bigint UNIQUE CHECK(owner_id>0), operator_id text UNIQUE REFERENCES operators(id)
);
INSERT INTO boss_approval_principals(key,name,owner_id) VALUES
 ('tony_tan','Tony Tan',NULL),('jason_pu','Jason Pu',2),('alex_huang','Alex Huang',NULL)
 ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS boss_approval_sources (
 order_id bigint PRIMARY KEY CHECK(order_id>0), tranid text NOT NULL,
 observed_status text NOT NULL, observed_at timestamptz NOT NULL,
 generation bigint NOT NULL DEFAULT 1, enriched_generation bigint NOT NULL DEFAULT 0,
 phase text NOT NULL DEFAULT '', snapshot jsonb,
 available_at timestamptz NOT NULL DEFAULT now(), lease_token uuid, lease_until timestamptz,
 attempts integer NOT NULL DEFAULT 0, last_error text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS boss_approval_sources_due ON boss_approval_sources(available_at) WHERE generation>enriched_generation;
CREATE TABLE IF NOT EXISTS boss_approval_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id bigint NOT NULL REFERENCES boss_approval_sources(order_id), cycle integer NOT NULL,
 status text NOT NULL CHECK(status IN ('pending','processing','approved','rejected','resolved')),
 revision bigint NOT NULL DEFAULT 1, snapshot jsonb NOT NULL, fingerprint text NOT NULL,
 recipients text[] NOT NULL DEFAULT '{}', actor_id text REFERENCES operators(id), actor_name text,
 created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz,
 last_error text NOT NULL DEFAULT '', UNIQUE(order_id,cycle)
);
CREATE UNIQUE INDEX IF NOT EXISTS boss_approval_requests_active ON boss_approval_requests(order_id) WHERE status IN ('pending','processing');
CREATE TABLE IF NOT EXISTS boss_approval_commands (
 id uuid PRIMARY KEY, request_id bigint NOT NULL REFERENCES boss_approval_requests(id),
 actor_id text NOT NULL REFERENCES operators(id), actor_name text NOT NULL,
 action text NOT NULL CHECK(action IN ('accept','reject')),
 status text NOT NULL CHECK(status IN ('queued','sending','uncertain','succeeded','failed')),
 snapshot jsonb NOT NULL, fingerprint text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 available_at timestamptz NOT NULL DEFAULT now(), lease_token uuid, lease_until timestamptz,
 attempts integer NOT NULL DEFAULT 0, remote_attempted_at timestamptz, last_error text NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS boss_approval_commands_active ON boss_approval_commands(request_id) WHERE status IN ('queued','sending','uncertain');
CREATE TABLE IF NOT EXISTS boss_approval_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 request_id bigint NOT NULL REFERENCES boss_approval_requests(id),
 kind text NOT NULL, actor_id text REFERENCES operators(id), actor_name text,
 snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS boss_approval_notifications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id bigint NOT NULL REFERENCES boss_approval_events(id),
 operator_id text NOT NULL REFERENCES operators(id), email text NOT NULL,
 read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
 email_status text NOT NULL DEFAULT 'pending' CHECK(email_status IN ('pending','sending','sent','failed','uncertain','cancelled')),
 attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(),
 lease_token uuid, lease_until timestamptz, last_error text NOT NULL DEFAULT '',
 UNIQUE(event_id,operator_id)
);
CREATE INDEX IF NOT EXISTS boss_approval_notifications_recipient ON boss_approval_notifications(operator_id,id DESC);
