CREATE OR REPLACE VIEW sales_orders AS
SELECT
  netsuite_id,
  tranid,
  trandate,
  customer_id,
  customer,
  status,
  status_text,
  foreign_total,
  order_location_id,
  order_location,
  outbound_location_id,
  outbound_location,
  delivery_method_id,
  delivery_method AS sales_order_type,
  memo,
  expected_delivery_date,
  dispatch_address,
  dispatch_window_start,
  dispatch_window_end,
  dispatch_instructions,
  operator_status,
  local_yard_order_status,
  netsuite_active,
  synced_at,
  dispatch_parse_source,
  dispatch_note_hash,
  dispatch_parsed_at,
  fulfillment_status,
  dispatch_planned,
  dispatch_plan_date,
  dispatch_truck_plate,
  dispatch_load_name,
  dispatch_parking_spot,
  dispatch_planned_at,
  netsuite_missing_at
FROM delivery_orders
WHERE order_type = 'sales_order';

CREATE OR REPLACE VIEW sales_order_lines AS
SELECT
  l.id,
  l.order_id AS sales_order_id,
  l.line_id,
  l.item_id,
  l.item_name,
  l.sku,
  l.item_description,
  l.item_type,
  l.item_type_text,
  l.quantity,
  l.unit,
  l.pallet_qty,
  l.layer_qty,
  l.section_qty,
  l.piece_qty,
  l.to_plt,
  l.to_lyr,
  l.to_sec,
  l.to_pcs,
  l.packed_pallet_qty,
  l.packed_layer_qty,
  l.packed_section_qty,
  l.packed_piece_qty,
  l.confirmed,
  l.confirmed_at,
  l.loaded_qty,
  l.loaded_uom,
  l.netsuite_active,
  l.sync_exception,
  l.synced_at,
  l.location_id,
  l.location
FROM delivery_order_lines l
JOIN delivery_orders o ON o.netsuite_id = l.order_id
WHERE o.order_type = 'sales_order';

CREATE OR REPLACE VIEW transfer_orders AS
SELECT
  COALESCE(d.netsuite_id, r.netsuite_id) AS netsuite_id,
  COALESCE(d.tranid, r.tranid) AS tranid,
  COALESCE(d.trandate, r.trandate) AS trandate,
  COALESCE(d.status, r.status) AS status,
  COALESCE(d.status_text, r.status_text) AS status_text,
  COALESCE(d.source_location_id, r.source_location_id, d.outbound_location_id) AS from_location_id,
  COALESCE(d.source_location, r.source_location, d.outbound_location) AS from_location,
  COALESCE(d.destination_location_id, r.destination_location_id) AS to_location_id,
  COALESCE(d.destination_location, r.destination_location) AS to_location,
  d.operator_status AS outbound_operator_status,
  r.receipt_status AS receiving_status,
  COALESCE(d.netsuite_active, r.netsuite_active, true) AS netsuite_active,
  GREATEST(COALESCE(d.synced_at, '-infinity'::timestamptz), COALESCE(r.synced_at, '-infinity'::timestamptz)) AS synced_at,
  COALESCE(d.memo, r.memo) AS memo,
  COALESCE(d.expected_delivery_date, r.expected_delivery_date) AS expected_delivery_date,
  COALESCE(d.dispatch_address, r.dispatch_address) AS dispatch_address,
  COALESCE(d.dispatch_window_start, r.dispatch_window_start) AS dispatch_window_start,
  COALESCE(d.dispatch_window_end, r.dispatch_window_end) AS dispatch_window_end,
  COALESCE(d.dispatch_instructions, r.dispatch_instructions) AS dispatch_instructions,
  COALESCE(d.dispatch_parse_source, r.dispatch_parse_source) AS dispatch_parse_source,
  COALESCE(d.dispatch_note_hash, r.dispatch_note_hash) AS dispatch_note_hash,
  GREATEST(COALESCE(d.dispatch_parsed_at, '-infinity'::timestamptz), COALESCE(r.dispatch_parsed_at, '-infinity'::timestamptz)) AS dispatch_parsed_at,
  d.local_yard_order_status,
  d.fulfillment_status,
  d.dispatch_planned,
  d.dispatch_plan_date,
  d.dispatch_truck_plate,
  d.dispatch_load_name,
  d.dispatch_parking_spot,
  d.dispatch_planned_at,
  COALESCE(d.netsuite_missing_at, r.netsuite_missing_at) AS netsuite_missing_at
FROM (SELECT * FROM delivery_orders WHERE order_type = 'transfer_order') d
FULL JOIN (SELECT * FROM receiving_orders WHERE order_type = 'transfer_order') r
  ON r.netsuite_id = d.netsuite_id;

CREATE OR REPLACE VIEW transfer_order_lines AS
SELECT
  'outbound' AS line_stage,
  l.id,
  l.order_id AS transfer_order_id,
  l.line_id,
  l.item_id,
  l.item_name,
  l.sku,
  l.item_description,
  l.quantity,
  l.unit,
  l.pallet_qty,
  l.layer_qty,
  l.section_qty,
  l.piece_qty,
  l.loaded_qty,
  l.loaded_uom,
  l.netsuite_active,
  l.sync_exception,
  l.synced_at,
  l.item_type,
  l.item_type_text,
  l.location_id,
  l.location,
  l.to_plt,
  l.to_lyr,
  l.to_sec,
  l.to_pcs,
  l.packed_pallet_qty,
  l.packed_layer_qty,
  l.packed_section_qty,
  l.packed_piece_qty,
  0::numeric AS received_pallet_qty,
  0::numeric AS received_layer_qty,
  0::numeric AS received_section_qty,
  0::numeric AS received_piece_qty,
  0::numeric AS netsuite_received_qty
FROM delivery_order_lines l
JOIN delivery_orders o ON o.netsuite_id = l.order_id
WHERE o.order_type = 'transfer_order'
UNION ALL
SELECT
  'receiving' AS line_stage,
  l.id,
  l.order_id AS transfer_order_id,
  l.line_id,
  l.item_id,
  l.item_name,
  l.sku,
  l.item_description,
  l.quantity,
  l.unit,
  l.pallet_qty,
  l.layer_qty,
  l.section_qty,
  l.piece_qty,
  l.netsuite_received_qty AS loaded_qty,
  l.unit AS loaded_uom,
  l.netsuite_active,
  l.sync_exception,
  l.synced_at,
  l.item_type,
  l.item_type_text,
  l.location_id,
  l.location,
  l.to_plt,
  l.to_lyr,
  l.to_sec,
  l.to_pcs,
  0::numeric AS packed_pallet_qty,
  0::numeric AS packed_layer_qty,
  0::numeric AS packed_section_qty,
  0::numeric AS packed_piece_qty,
  l.received_pallet_qty,
  l.received_layer_qty,
  l.received_section_qty,
  l.received_piece_qty,
  l.netsuite_received_qty
FROM receiving_order_lines l
JOIN receiving_orders o ON o.netsuite_id = l.order_id
WHERE o.order_type = 'transfer_order';

CREATE OR REPLACE VIEW purchase_orders AS
SELECT
  netsuite_id,
  tranid,
  trandate,
  vendor_id,
  vendor,
  status,
  status_text,
  foreign_total,
  destination_location_id,
  destination_location,
  memo,
  dispatch_vendor_yard,
  dispatch_address,
  dispatch_window_start,
  dispatch_window_end,
  dispatch_instructions,
  receipt_status,
  netsuite_active,
  synced_at,
  source_location_id,
  source_location,
  expected_delivery_date,
  dispatch_parse_source,
  dispatch_note_hash,
  dispatch_parsed_at,
  netsuite_missing_at
FROM receiving_orders
WHERE order_type = 'purchase_order';

CREATE OR REPLACE VIEW purchase_order_lines AS
SELECT
  l.id,
  l.order_id AS purchase_order_id,
  l.line_id,
  l.item_id,
  l.item_name,
  l.sku,
  l.item_description,
  l.item_type,
  l.item_type_text,
  l.quantity,
  l.unit,
  l.location_id,
  l.location,
  l.pallet_qty,
  l.layer_qty,
  l.section_qty,
  l.piece_qty,
  l.to_plt,
  l.to_lyr,
  l.to_sec,
  l.to_pcs,
  l.received_pallet_qty,
  l.received_layer_qty,
  l.received_section_qty,
  l.received_piece_qty,
  l.netsuite_received_qty,
  l.netsuite_active,
  l.sync_exception,
  l.synced_at
FROM receiving_order_lines l
JOIN receiving_orders o ON o.netsuite_id = l.order_id
WHERE o.order_type = 'purchase_order';
